# Generated by Django 2.2.3 on 2019-07-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('food_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='monto total')),
                ('food_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_sessions.FoodSession')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='monto total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SessionUser')),
            ],
        ),
        migrations.CreateModel(
            name='FoodSessionBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='monto total')),
                ('food_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_sessions.FoodSession')),
            ],
        ),
    ]
