# Generated by Django 2.2.3 on 2019-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_sharedbill_total_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbill',
            name='total_per_person',
            field=models.FloatField(verbose_name='total por persona'),
        ),
    ]
