# Generated by Django 2.2.3 on 2019-07-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_sessions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('amount', models.FloatField(verbose_name='monto')),
                ('food_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_sessions.FoodSession')),
            ],
            options={
                'verbose_name': 'artículo compartido',
                'verbose_name_plural': 'artículos compartidos',
            },
        ),
        migrations.CreateModel(
            name='PersonalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('amount', models.FloatField(verbose_name='monto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SessionUser')),
            ],
            options={
                'verbose_name': 'artículo personal',
                'verbose_name_plural': 'artículos personales',
            },
        ),
    ]
