# Generated by Django 2.2.3 on 2019-07-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_sessions', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_sessions.FoodSession')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
            options={
                'verbose_name': 'artículo compartido',
                'verbose_name_plural': 'artículos compartidos',
            },
        ),
    ]
