# Generated by Django 2.2.3 on 2019-07-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_shareditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SessionUser'),
        ),
    ]
