# Generated by Django 2.2.3 on 2019-07-19 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=False, verbose_name='activa')),
                ('total_amount', models.FloatField(blank=True, default=0, verbose_name='monto total')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='fecha de creacion')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='última modificación')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
            ],
            options={
                'verbose_name': 'sesión de comida',
                'verbose_name_plural': 'sesiones de comida',
            },
        ),
    ]
