# Generated by Django 2.2.3 on 2019-07-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsession',
            name='total_amount',
        ),
    ]
